[character]
vimcmd_symbol = '[\(N\) ðŸ¤ª](bold cyan) '
success_symbol = '[\(I\) ðŸ¤ ](bold green)'
error_symbol = '[\(I\) ðŸ˜­](bold red)'
vimcmd_replace_one_symbol = "[ðŸ¤©](bold magenta)"
vimcmd_replace_symbol = "[ðŸ¤©](bold magenta)"
vimcmd_visual_symbol = '[\(V\) ðŸ¤©](bold yellow) '

[directory]
truncate_to_repo = false
truncation_length = 4
truncation_symbol = ".../"
home_symbol = "~"
format = '[ $path]($style)[$read_only]($read_only_style) '
style = "#d79921"                                          # gruvbox yellow

[git_status]
modified = " mod!"   # !
staged = " stag+"    # +
untracked = " untr?" # ?
behind = " behâ‡£"     # "â‡£"
ahead = " aheadâ‡¡"    # "â‡¡"

[package]
format = ''
symbol = ""
style = "bold #f1fa8c" # You can customize the color

[rust]
format = '[$symbol\(rust: $version\)]($style) ' # Removed the "via" text
symbol = ""
style = "bold red"                              # Custom color
